[connections.default]
account = "HO60700"
username = "MSNANDA"
password = "Maninder@12345"
role = "ACCOUNTADMIN"
SNOWFLAKE_ACCOUNT = "HO60700"
SNOWFLAKE_USER  = "MSNANDA"
SNOWFLAKE_PASSWORD = "Maninder@12345"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"